pipeline:
  init:
    image: codeberg.org/${CI_REPO_OWNER}/vercel
    commands:
      - vercel --token $${VERCEL} project add chloewinkel
      - vercel --token $${VERCEL} link -p chloewinkel --yes
    secrets: [ VERCEL ]
    when:
      event:
        - push
        - manual
  deploy-preview:
    image: codeberg.org/${CI_REPO_OWNER}/vercel
    commands:
      - vercel --token $${VERCEL} pull
      - vercel --token $${VERCEL}
    secrets: [ VERCEL ]
    when:
      event:
        - push
        - manual
