pipeline:
  publish-vercel-image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/vercel
      registry: codeberg.org
      dockerfile: .woodpecker/images/Dockerfile-vercel
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      - path:
          include: [ '.woodpecker/publish-vercel-image.yaml', '.woodpecker/images/Dockerfile-vercel' ]
